service: product-service
frameworkVersion: '3'
variablesResolutionMode: 20210219

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    ENV_STAGE: ${opt:stage, 'dev'}
    CONNECTION_STR: ''
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: '*'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

resources:
  Resources:
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    CreateProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Create Product Topic
        TopicName: createProductTopic

    ProductEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        TopicArn: !Ref CreateProductTopic
        Endpoint: mariia_zaiets@epam.com

    FilteredProductEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        TopicArn: !Ref CreateProductTopic
        Endpoint: mariiazaiets09@gmail.com
        FilterPolicy:
          price: [100, 200]

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
    vpc:
      securityGroupIds:
        - sg-0d3aaf5f0dc6ceba9
      subnetIds:
        - subnet-0b3f5462358873117
        - subnet-0dade5e03fa7f3ee8
        - subnet-02f8d70e6ce1c02e6

  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
    vpc:
      securityGroupIds:
        - sg-0d3aaf5f0dc6ceba9
      subnetIds:
        - subnet-0b3f5462358873117
        - subnet-0dade5e03fa7f3ee8
        - subnet-02f8d70e6ce1c02e6

  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
    vpc:
      securityGroupIds:
        - sg-0d3aaf5f0dc6ceba9
      subnetIds:
        - subnet-0b3f5462358873117
        - subnet-0dade5e03fa7f3ee8
        - subnet-02f8d70e6ce1c02e6

  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    environment:
      CONNECTION_STR: ''
      SNS_TOPIC_ARN: !Ref CreateProductTopic
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CatalogItemsQueue
              - Arn
          batchSize: 5
